# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

box       = 'precise64'
url       = 'http://files.vagrantup.com/precise64.box'
hostname  = 'TeamCity01'
ram       = '512'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Standard configuration
  config.vm.box = box
  config.vm.box_url = url
  config.vm.hostname = hostname
  config.vm.network :forwarded_port, guest: 8111, host: 8111
  
  # Configure provider
  config.vm.provider "virtualbox" do |v|
    v.customize [
	'modifyvm', :id,
	'--name', hostname,
	'--memory', ram
  ]
  end
  
  # Provision
  config.vm.provision :shell, :path => "TeamCity_setup.sh"

end
